export const PRODUCTS = [
  {
    id: 1,
    title: "Портативный Очиститель Масла Серии BLYJ",
    manufacturer: "KNELSON",
    status: "in_stock",       
    type: "fuel",           
    power: 220,
    img: "/images/filters1.svg",
    popularity: 5,
  },
  {
    id: 2,
    title: "Фильтр Гидравлический СМ-45",
    manufacturer: "DONALDSON",
    status: "preorder",
    type: "oil",
    power: 280,
    img: "/images/filters2.svg",
    popularity: 3,
  },
  {
    id: 3,
    title: "Сменный Картридж SKF-150",
    manufacturer: "BIG FILTER",
    status: "in_stock",
    type: "air",
    power: 120,
    img: "/images/filters3.svg",
    popularity: 9,
  },
  {
    id: 4,
    title: "Промышленный Маслофильтр КФР-88",
    manufacturer: "MICRO",
    status: "in_stock",
    type: "pump",
    power: 500,
    img: "/images/filters4.svg",
    popularity: 1,
  },
  {
    id: 5,
    title: "Очиститель Масла серии ЛМГ-12",
    manufacturer: "MANN FILTER",
    status: "preorder",
    type: "fuel",
    power: 600,
    img: "/images/filters5.svg",
    popularity: 7,
  },
  {
    id: 6,
    title: "Портативный Очиститель Масла Серии BLYJ",
    manufacturer: "KNELSON",
    status: "in_stock",
    type: "oil",
    power: 220,
    img: "/images/filters6.svg",
    popularity: 4,
  },
  {
    id: 7,
    title: "Портативный Очиститель Масла Серии BLYJ",
    manufacturer: "KNELSON",
    status: "in_stock",
    type: "air",
    power: 280,
    img: "/images/filters7.svg",
    popularity: 2,
  },
  {
    id: 8,
    title: "Портативный Очиститель Масла Серии BLYJ",
    manufacturer: "KNELSON",
    status: "preorder",
    type: "pump",
    power: 120,
    img: "/images/filters8.svg",
    popularity: 8,
  },
];

export const CAPACITY_OPTIONS = [100000, 250000, 800000, 1000000];
export const VOLTAGE_OPTIONS  = [120, 220, 280, 500, 600];
